# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MountGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MountGui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 300)
        MainWindow.setMinimumSize(QtCore.QSize(550, 300))
        MainWindow.setMaximumSize(QtCore.QSize(550, 300))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/ubuntu/odrive-x/icon/odrive.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.remote_path = QtWidgets.QLineEdit(self.groupBox)
        self.remote_path.setObjectName("remote_path")
        self.gridLayout.addWidget(self.remote_path, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.btn_cloud = QtWidgets.QPushButton(self.groupBox)
        self.btn_cloud.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_cloud.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/ubuntu/odrive-x/icon/internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cloud.setIcon(icon1)
        self.btn_cloud.setIconSize(QtCore.QSize(20, 20))
        self.btn_cloud.setObjectName("btn_cloud")
        self.gridLayout.addWidget(self.btn_cloud, 3, 1, 1, 1)
        self.btn_local = QtWidgets.QPushButton(self.groupBox)
        self.btn_local.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_local.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/home/ubuntu/odrive-x/icon/browse-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_local.setIcon(icon2)
        self.btn_local.setIconSize(QtCore.QSize(20, 20))
        self.btn_local.setObjectName("btn_local")
        self.gridLayout.addWidget(self.btn_local, 1, 1, 1, 1)
        self.local_path = QtWidgets.QLineEdit(self.groupBox)
        self.local_path.setObjectName("local_path")
        self.gridLayout.addWidget(self.local_path, 1, 0, 1, 1)
        self.btn_mount = QtWidgets.QPushButton(self.groupBox)
        self.btn_mount.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_mount.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/home/ubuntu/odrive-x/icon/pack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mount.setIcon(icon3)
        self.btn_mount.setIconSize(QtCore.QSize(20, 20))
        self.btn_mount.setObjectName("btn_mount")
        self.gridLayout.addWidget(self.btn_mount, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "odrive-x"))
        self.groupBox.setTitle(_translate("MainWindow", "Mount"))
        self.label.setText(_translate("MainWindow", "Select local path"))
        self.remote_path.setText(_translate("MainWindow", "/"))
        self.label_2.setText(_translate("MainWindow", "Select remote path"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MountGui()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
